spring:
  rabbitmq:   #连接远端虚拟机中docker中安装的rabbit
    host: 192.168.5.112
    port: 5672
    username: guest
    password: guest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: xiaojian123
    url: jdbc:mysql://127.0.0.1:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
env:
  test555
girl:
  name: lili
  age: 18  
